import type { APIResponse, PaginationInfo } from '../types/Character';

const MOCK_CHARACTERS = [
  // Original Trilogy
  {
    name: 'Luke Skywalker',
    height: '172',
    mass: '77',
    hair_color: 'blond',
    skin_color: 'fair',
    eye_color: 'blue',
    birth_year: '19BBY',
    gender: 'male',
    homeworld: 'https://swapi.dev/api/planets/1/',
    films: ['https://swapi.dev/api/films/1/'],
    species: [],
    vehicles: ['https://swapi.dev/api/vehicles/14/'],
    starships: ['https://swapi.dev/api/starships/12/'],
    created: '2014-12-09T13:50:51.644000Z',
    edited: '2014-12-20T21:17:56.891000Z',
    url: 'https://swapi.dev/api/people/1/',
  },
  {
    name: 'Darth Vader',
    height: '202',
    mass: '136',
    hair_color: 'none',
    skin_color: 'white',
    eye_color: 'yellow',
    birth_year: '41.9BBY',
    gender: 'male',
    homeworld: 'https://swapi.dev/api/planets/1/',
    films: ['https://swapi.dev/api/films/1/'],
    species: [],
    vehicles: [],
    starships: ['https://swapi.dev/api/starships/13/'],
    created: '2014-12-10T15:18:20.704000Z',
    edited: '2014-12-20T21:17:50.313000Z',
    url: 'https://swapi.dev/api/people/4/',
  },
  {
    name: 'Leia Organa',
    height: '150',
    mass: '49',
    hair_color: 'brown',
    skin_color: 'light',
    eye_color: 'brown',
    birth_year: '19BBY',
    gender: 'female',
    homeworld: 'https://swapi.dev/api/planets/2/',
    films: ['https://swapi.dev/api/films/1/'],
    species: [],
    vehicles: ['https://swapi.dev/api/vehicles/30/'],
    starships: [],
    created: '2014-12-10T15:20:09.791000Z',
    edited: '2014-12-20T21:17:50.315000Z',
    url: 'https://swapi.dev/api/people/5/',
  },
  {
    name: 'Han Solo',
    height: '180',
    mass: '80',
    hair_color: 'brown',
    skin_color: 'fair',
    eye_color: 'brown',
    birth_year: '29BBY',
    gender: 'male',
    homeworld: 'https://swapi.dev/api/planets/22/',
    films: ['https://swapi.dev/api/films/1/'],
    species: [],
    vehicles: [],
    starships: ['https://swapi.dev/api/starships/10/'],
    created: '2014-12-10T16:49:14.582000Z',
    edited: '2014-12-20T21:17:50.334000Z',
    url: 'https://swapi.dev/api/people/14/',
  },
  {
    name: 'Chewbacca',
    height: '228',
    mass: '112',
    hair_color: 'brown',
    skin_color: 'unknown',
    eye_color: 'blue',
    birth_year: '200BBY',
    gender: 'male',
    homeworld: 'https://swapi.dev/api/planets/14/',
    films: ['https://swapi.dev/api/films/1/'],
    species: ['https://swapi.dev/api/species/3/'],
    vehicles: ['https://swapi.dev/api/vehicles/19/'],
    starships: ['https://swapi.dev/api/starships/10/'],
    created: '2014-12-10T16:42:45.066000Z',
    edited: '2014-12-20T21:17:50.332000Z',
    url: 'https://swapi.dev/api/people/13/',
  },
  {
    name: 'Obi-Wan Kenobi',
    height: '182',
    mass: '77',
    hair_color: 'auburn, white',
    skin_color: 'fair',
    eye_color: 'blue-gray',
    birth_year: '57BBY',
    gender: 'male',
    homeworld: 'https://swapi.dev/api/planets/20/',
    films: ['https://swapi.dev/api/films/1/'],
    species: [],
    vehicles: ['https://swapi.dev/api/vehicles/38/'],
    starships: ['https://swapi.dev/api/starships/48/'],
    created: '2014-12-10T16:16:29.192000Z',
    edited: '2014-12-20T21:17:50.325000Z',
    url: 'https://swapi.dev/api/people/10/',
  },
  {
    name: 'C-3PO',
    height: '167',
    mass: '75',
    hair_color: 'n/a',
    skin_color: 'gold',
    eye_color: 'yellow',
    birth_year: '112BBY',
    gender: 'n/a',
    homeworld: 'https://swapi.dev/api/planets/1/',
    films: ['https://swapi.dev/api/films/1/'],
    species: ['https://swapi.dev/api/species/2/'],
    vehicles: [],
    starships: [],
    created: '2014-12-10T15:10:51.357000Z',
    edited: '2014-12-20T21:17:50.309000Z',
    url: 'https://swapi.dev/api/people/2/',
  },
  {
    name: 'R2-D2',
    height: '96',
    mass: '32',
    hair_color: 'n/a',
    skin_color: 'white, blue',
    eye_color: 'red',
    birth_year: '33BBY',
    gender: 'n/a',
    homeworld: 'https://swapi.dev/api/planets/8/',
    films: ['https://swapi.dev/api/films/1/'],
    species: ['https://swapi.dev/api/species/2/'],
    vehicles: [],
    starships: [],
    created: '2014-12-10T15:11:50.376000Z',
    edited: '2014-12-20T21:17:50.311000Z',
    url: 'https://swapi.dev/api/people/3/',
  },
  // Prequel Trilogy
  {
    name: 'Anakin Skywalker',
    height: '188',
    mass: '84',
    hair_color: 'blond',
    skin_color: 'fair',
    eye_color: 'blue',
    birth_year: '41.9BBY',
    gender: 'male',
    homeworld: 'https://swapi.dev/api/planets/1/',
    films: ['https://swapi.dev/api/films/4/'],
    species: [],
    vehicles: ['https://swapi.dev/api/vehicles/44/'],
    starships: ['https://swapi.dev/api/starships/39/'],
    created: '2014-12-10T16:20:44.310000Z',
    edited: '2014-12-20T21:17:50.327000Z',
    url: 'https://swapi.dev/api/people/11/',
  },
  {
    name: 'Padmé Amidala',
    height: '185',
    mass: '45',
    hair_color: 'brown',
    skin_color: 'light',
    eye_color: 'brown',
    birth_year: '46BBY',
    gender: 'female',
    homeworld: 'https://swapi.dev/api/planets/8/',
    films: ['https://swapi.dev/api/films/4/'],
    species: [],
    vehicles: [],
    starships: ['https://swapi.dev/api/starships/39/'],
    created: '2014-12-19T17:28:26.926000Z',
    edited: '2014-12-20T21:17:50.401000Z',
    url: 'https://swapi.dev/api/people/27/',
  },
  {
    name: 'Yoda',
    height: '66',
    mass: '17',
    hair_color: 'white',
    skin_color: 'green',
    eye_color: 'brown',
    birth_year: '896BBY',
    gender: 'male',
    homeworld: 'https://swapi.dev/api/planets/28/',
    films: ['https://swapi.dev/api/films/2/'],
    species: ['https://swapi.dev/api/species/6/'],
    vehicles: [],
    starships: [],
    created: '2014-12-15T12:26:01.042000Z',
    edited: '2014-12-20T21:17:50.345000Z',
    url: 'https://swapi.dev/api/people/20/',
  },
  {
    name: 'Mace Windu',
    height: '188',
    mass: '84',
    hair_color: 'none',
    skin_color: 'dark',
    eye_color: 'brown',
    birth_year: '72BBY',
    gender: 'male',
    homeworld: 'https://swapi.dev/api/planets/22/',
    films: ['https://swapi.dev/api/films/4/'],
    species: [],
    vehicles: [],
    starships: [],
    created: '2014-12-20T21:17:50.375000Z',
    edited: '2014-12-20T21:17:50.375000Z',
    url: 'https://swapi.dev/api/people/51/',
  },
  {
    name: 'Qui-Gon Jinn',
    height: '193',
    mass: '89',
    hair_color: 'brown',
    skin_color: 'fair',
    eye_color: 'blue',
    birth_year: '92BBY',
    gender: 'male',
    homeworld: 'https://swapi.dev/api/planets/28/',
    films: ['https://swapi.dev/api/films/4/'],
    species: [],
    vehicles: ['https://swapi.dev/api/vehicles/38/'],
    starships: [],
    created: '2014-12-19T16:54:53.618000Z',
    edited: '2014-12-20T21:17:50.375000Z',
    url: 'https://swapi.dev/api/people/32/',
  },
  {
    name: 'Palpatine',
    height: '170',
    mass: '75',
    hair_color: 'grey',
    skin_color: 'pale',
    eye_color: 'yellow',
    birth_year: '82BBY',
    gender: 'male',
    homeworld: 'https://swapi.dev/api/planets/8/',
    films: ['https://swapi.dev/api/films/4/'],
    species: [],
    vehicles: [],
    starships: [],
    created: '2014-12-15T12:48:05.971000Z',
    edited: '2014-12-20T21:17:50.347000Z',
    url: 'https://swapi.dev/api/people/21/',
  },
  {
    name: 'Count Dooku',
    height: '193',
    mass: '80',
    hair_color: 'white',
    skin_color: 'fair',
    eye_color: 'brown',
    birth_year: '102BBY',
    gender: 'male',
    homeworld: 'https://swapi.dev/api/planets/7/',
    films: ['https://swapi.dev/api/films/5/'],
    species: [],
    vehicles: ['https://swapi.dev/api/vehicles/55/'],
    starships: [],
    created: '2014-12-20T21:17:50.408000Z',
    edited: '2014-12-20T21:17:50.408000Z',
    url: 'https://swapi.dev/api/people/67/',
  },
  {
    name: 'Jar Jar Binks',
    height: '196',
    mass: '66',
    hair_color: 'none',
    skin_color: 'orange',
    eye_color: 'orange',
    birth_year: '52BBY',
    gender: 'male',
    homeworld: 'https://swapi.dev/api/planets/8/',
    films: ['https://swapi.dev/api/films/4/'],
    species: ['https://swapi.dev/api/species/12/'],
    vehicles: [],
    starships: [],
    created: '2014-12-19T17:29:32.489000Z',
    edited: '2014-12-20T21:17:50.383000Z',
    url: 'https://swapi.dev/api/people/36/',
  },
  {
    name: 'General Grievous',
    height: '216',
    mass: '159',
    hair_color: 'none',
    skin_color: 'brown, white',
    eye_color: 'green, yellow',
    birth_year: 'unknown',
    gender: 'male',
    homeworld: 'https://swapi.dev/api/planets/23/',
    films: ['https://swapi.dev/api/films/6/'],
    species: ['https://swapi.dev/api/species/28/'],
    vehicles: ['https://swapi.dev/api/vehicles/60/'],
    starships: ['https://swapi.dev/api/starships/74/'],
    created: '2014-12-20T21:17:50.395000Z',
    edited: '2014-12-20T21:17:50.395000Z',
    url: 'https://swapi.dev/api/people/79/',
  },
  // Additional Characters
  {
    name: 'Boba Fett',
    height: '183',
    mass: '78.2',
    hair_color: 'black',
    skin_color: 'fair',
    eye_color: 'brown',
    birth_year: '31.5BBY',
    gender: 'male',
    homeworld: 'https://swapi.dev/api/planets/10/',
    films: ['https://swapi.dev/api/films/2/'],
    species: [],
    vehicles: [],
    starships: ['https://swapi.dev/api/starships/21/'],
    created: '2014-12-15T12:49:32.457000Z',
    edited: '2014-12-20T21:17:50.349000Z',
    url: 'https://swapi.dev/api/people/22/',
  },
  {
    name: 'Jango Fett',
    height: '183',
    mass: '79',
    hair_color: 'black',
    skin_color: 'tan',
    eye_color: 'brown',
    birth_year: '66BBY',
    gender: 'male',
    homeworld: 'https://swapi.dev/api/planets/53/',
    films: ['https://swapi.dev/api/films/5/'],
    species: [],
    vehicles: [],
    starships: [],
    created: '2014-12-20T21:17:50.383000Z',
    edited: '2014-12-20T21:17:50.383000Z',
    url: 'https://swapi.dev/api/people/79/',
  },
  {
    name: 'Lando Calrissian',
    height: '177',
    mass: '79',
    hair_color: 'black',
    skin_color: 'dark',
    eye_color: 'brown',
    birth_year: '31BBY',
    gender: 'male',
    homeworld: 'https://swapi.dev/api/planets/30/',
    films: ['https://swapi.dev/api/films/2/'],
    species: [],
    vehicles: [],
    starships: ['https://swapi.dev/api/starships/10/'],
    created: '2014-12-15T12:56:32.683000Z',
    edited: '2014-12-20T21:17:50.357000Z',
    url: 'https://swapi.dev/api/people/25/',
  },
  // Clone Wars Era
  {
    name: 'Ahsoka Tano',
    height: '166',
    mass: '46',
    hair_color: 'none',
    skin_color: 'blue',
    eye_color: 'blue',
    birth_year: '36BBY',
    gender: 'female',
    homeworld: 'https://swapi.dev/api/planets/47/',
    films: [],
    species: ['https://swapi.dev/api/species/18/'],
    vehicles: [],
    starships: [],
    created: '2014-12-20T21:17:50.400000Z',
    edited: '2014-12-20T21:17:50.400000Z',
    url: 'https://swapi.dev/api/people/80/',
  },
  {
    name: 'Captain Rex',
    height: '183',
    mass: '78',
    hair_color: 'black',
    skin_color: 'tan',
    eye_color: 'brown',
    birth_year: '32BBY',
    gender: 'male',
    homeworld: 'https://swapi.dev/api/planets/10/',
    films: [],
    species: [],
    vehicles: [],
    starships: [],
    created: '2014-12-20T21:17:50.401000Z',
    edited: '2014-12-20T21:17:50.401000Z',
    url: 'https://swapi.dev/api/people/81/',
  },
  {
    name: 'Commander Cody',
    height: '183',
    mass: '78',
    hair_color: 'black',
    skin_color: 'tan',
    eye_color: 'brown',
    birth_year: '32BBY',
    gender: 'male',
    homeworld: 'https://swapi.dev/api/planets/10/',
    films: [],
    species: [],
    vehicles: [],
    starships: [],
    created: '2014-12-20T21:17:50.402000Z',
    edited: '2014-12-20T21:17:50.402000Z',
    url: 'https://swapi.dev/api/people/82/',
  },
  // Rebels Era
  {
    name: 'Kanan Jarrus',
    height: '191',
    mass: '77',
    hair_color: 'brown',
    skin_color: 'light',
    eye_color: 'green',
    birth_year: '33BBY',
    gender: 'male',
    homeworld: 'https://swapi.dev/api/planets/5/',
    films: [],
    species: [],
    vehicles: [],
    starships: [],
    created: '2014-12-20T21:17:50.403000Z',
    edited: '2014-12-20T21:17:50.403000Z',
    url: 'https://swapi.dev/api/people/83/',
  },
  {
    name: 'Ezra Bridger',
    height: '165',
    mass: '56',
    hair_color: 'black',
    skin_color: 'light',
    eye_color: 'blue',
    birth_year: '19BBY',
    gender: 'male',
    homeworld: 'https://swapi.dev/api/planets/22/',
    films: [],
    species: [],
    vehicles: [],
    starships: [],
    created: '2014-12-20T21:17:50.404000Z',
    edited: '2014-12-20T21:17:50.404000Z',
    url: 'https://swapi.dev/api/people/84/',
  },
  {
    name: 'Hera Syndulla',
    height: '175',
    mass: '50',
    hair_color: 'none',
    skin_color: 'green',
    eye_color: 'green',
    birth_year: '29BBY',
    gender: 'female',
    homeworld: 'https://swapi.dev/api/planets/37/',
    films: [],
    species: ['https://swapi.dev/api/species/15/'],
    vehicles: [],
    starships: [],
    created: '2014-12-20T21:17:50.405000Z',
    edited: '2014-12-20T21:17:50.405000Z',
    url: 'https://swapi.dev/api/people/85/',
  },
  {
    name: 'Sabine Wren',
    height: '166',
    mass: '45',
    hair_color: 'black',
    skin_color: 'light',
    eye_color: 'brown',
    birth_year: '21BBY',
    gender: 'female',
    homeworld: 'https://swapi.dev/api/planets/56/',
    films: [],
    species: [],
    vehicles: [],
    starships: [],
    created: '2014-12-20T21:17:50.406000Z',
    edited: '2014-12-20T21:17:50.406000Z',
    url: 'https://swapi.dev/api/people/86/',
  },
  {
    name: 'Zeb Orrelios',
    height: '190',
    mass: '75',
    hair_color: 'none',
    skin_color: 'purple',
    eye_color: 'green',
    birth_year: '28BBY',
    gender: 'male',
    homeworld: 'https://swapi.dev/api/planets/58/',
    films: [],
    species: ['https://swapi.dev/api/species/35/'],
    vehicles: [],
    starships: [],
    created: '2014-12-20T21:17:50.407000Z',
    edited: '2014-12-20T21:17:50.407000Z',
    url: 'https://swapi.dev/api/people/87/',
  },
  // Sequel Trilogy
  {
    name: 'Rey',
    height: '170',
    mass: '54',
    hair_color: 'brown',
    skin_color: 'light',
    eye_color: 'hazel',
    birth_year: '15ABY',
    gender: 'female',
    homeworld: 'https://swapi.dev/api/planets/60/',
    films: [],
    species: [],
    vehicles: [],
    starships: [],
    created: '2014-12-20T21:17:50.408000Z',
    edited: '2014-12-20T21:17:50.408000Z',
    url: 'https://swapi.dev/api/people/88/',
  },
  {
    name: 'Finn',
    height: '178',
    mass: '73',
    hair_color: 'black',
    skin_color: 'dark',
    eye_color: 'dark',
    birth_year: '11ABY',
    gender: 'male',
    homeworld: 'https://swapi.dev/api/planets/28/',
    films: [],
    species: [],
    vehicles: [],
    starships: [],
    created: '2014-12-20T21:17:50.409000Z',
    edited: '2014-12-20T21:17:50.409000Z',
    url: 'https://swapi.dev/api/people/89/',
  },
  {
    name: 'Poe Dameron',
    height: '172',
    mass: '80',
    hair_color: 'brown',
    skin_color: 'light',
    eye_color: 'brown',
    birth_year: '2ABY',
    gender: 'male',
    homeworld: 'https://swapi.dev/api/planets/28/',
    films: [],
    species: [],
    vehicles: [],
    starships: [],
    created: '2014-12-20T21:17:50.410000Z',
    edited: '2014-12-20T21:17:50.410000Z',
    url: 'https://swapi.dev/api/people/90/',
  },
  {
    name: 'Kylo Ren',
    height: '189',
    mass: '89',
    hair_color: 'black',
    skin_color: 'light',
    eye_color: 'brown',
    birth_year: '5ABY',
    gender: 'male',
    homeworld: 'https://swapi.dev/api/planets/28/',
    films: [],
    species: [],
    vehicles: [],
    starships: [],
    created: '2014-12-20T21:17:50.411000Z',
    edited: '2014-12-20T21:17:50.411000Z',
    url: 'https://swapi.dev/api/people/91/',
  },
  {
    name: 'Supreme Leader Snoke',
    height: '200',
    mass: 'unknown',
    hair_color: 'none',
    skin_color: 'pale',
    eye_color: 'blue',
    birth_year: 'unknown',
    gender: 'male',
    homeworld: 'https://swapi.dev/api/planets/28/',
    films: [],
    species: [],
    vehicles: [],
    starships: [],
    created: '2014-12-20T21:17:50.412000Z',
    edited: '2014-12-20T21:17:50.412000Z',
    url: 'https://swapi.dev/api/people/92/',
  },
  {
    name: 'Captain Phasma',
    height: '200',
    mass: 'unknown',
    hair_color: 'unknown',
    skin_color: 'unknown',
    eye_color: 'unknown',
    birth_year: 'unknown',
    gender: 'female',
    homeworld: 'https://swapi.dev/api/planets/28/',
    films: [],
    species: [],
    vehicles: [],
    starships: [],
    created: '2014-12-20T21:17:50.413000Z',
    edited: '2014-12-20T21:17:50.413000Z',
    url: 'https://swapi.dev/api/people/93/',
  },
  // The Mandalorian Era
  {
    name: 'Din Djarin',
    height: '183',
    mass: '80',
    hair_color: 'brown',
    skin_color: 'light',
    eye_color: 'brown',
    birth_year: '30BBY',
    gender: 'male',
    homeworld: 'https://swapi.dev/api/planets/58/',
    films: [],
    species: [],
    vehicles: [],
    starships: [],
    created: '2014-12-20T21:17:50.414000Z',
    edited: '2014-12-20T21:17:50.414000Z',
    url: 'https://swapi.dev/api/people/94/',
  },
  {
    name: 'Grogu',
    height: '66',
    mass: '6.5',
    hair_color: 'none',
    skin_color: 'green',
    eye_color: 'brown',
    birth_year: '41BBY',
    gender: 'male',
    homeworld: 'https://swapi.dev/api/planets/28/',
    films: [],
    species: ['https://swapi.dev/api/species/6/'],
    vehicles: [],
    starships: [],
    created: '2014-12-20T21:17:50.415000Z',
    edited: '2014-12-20T21:17:50.415000Z',
    url: 'https://swapi.dev/api/people/95/',
  },
  {
    name: 'Cara Dune',
    height: '173',
    mass: '70',
    hair_color: 'black',
    skin_color: 'light',
    eye_color: 'brown',
    birth_year: '21BBY',
    gender: 'female',
    homeworld: 'https://swapi.dev/api/planets/2/',
    films: [],
    species: [],
    vehicles: [],
    starships: [],
    created: '2014-12-20T21:17:50.416000Z',
    edited: '2014-12-20T21:17:50.416000Z',
    url: 'https://swapi.dev/api/people/96/',
  },
  {
    name: 'Greef Karga',
    height: '175',
    mass: '79',
    hair_color: 'black',
    skin_color: 'dark',
    eye_color: 'brown',
    birth_year: '52BBY',
    gender: 'male',
    homeworld: 'https://swapi.dev/api/planets/58/',
    films: [],
    species: [],
    vehicles: [],
    starships: [],
    created: '2014-12-20T21:17:50.417000Z',
    edited: '2014-12-20T21:17:50.417000Z',
    url: 'https://swapi.dev/api/people/97/',
  },
  {
    name: 'Moff Gideon',
    height: '183',
    mass: '90',
    hair_color: 'black',
    skin_color: 'dark',
    eye_color: 'brown',
    birth_year: '31BBY',
    gender: 'male',
    homeworld: 'https://swapi.dev/api/planets/28/',
    films: [],
    species: [],
    vehicles: [],
    starships: [],
    created: '2014-12-20T21:17:50.418000Z',
    edited: '2014-12-20T21:17:50.418000Z',
    url: 'https://swapi.dev/api/people/98/',
  },
  // Additional Extended Universe Characters
  {
    name: 'Grand Admiral Thrawn',
    height: '191',
    mass: '77',
    hair_color: 'none',
    skin_color: 'blue',
    eye_color: 'red',
    birth_year: '59BBY',
    gender: 'male',
    homeworld: 'https://swapi.dev/api/planets/60/',
    films: [],
    species: ['https://swapi.dev/api/species/15/'],
    vehicles: [],
    starships: [],
    created: '2014-12-20T21:17:50.419000Z',
    edited: '2014-12-20T21:17:50.419000Z',
    url: 'https://swapi.dev/api/people/99/',
  },
  {
    name: 'Bo-Katan Kryze',
    height: '175',
    mass: '57',
    hair_color: 'blonde',
    skin_color: 'light',
    eye_color: 'green',
    birth_year: '67BBY',
    gender: 'female',
    homeworld: 'https://swapi.dev/api/planets/56/',
    films: [],
    species: [],
    vehicles: [],
    starships: [],
    created: '2014-12-20T21:17:50.420000Z',
    edited: '2014-12-20T21:17:50.420000Z',
    url: 'https://swapi.dev/api/people/100/',
  },
  {
    name: 'Fennec Shand',
    height: '166',
    mass: '50',
    hair_color: 'black',
    skin_color: 'light',
    eye_color: 'brown',
    birth_year: '31BBY',
    gender: 'female',
    homeworld: 'https://swapi.dev/api/planets/1/',
    films: [],
    species: [],
    vehicles: [],
    starships: [],
    created: '2014-12-20T21:17:50.421000Z',
    edited: '2014-12-20T21:17:50.421000Z',
    url: 'https://swapi.dev/api/people/101/',
  },
  {
    name: 'Cad Bane',
    height: '185',
    mass: '75',
    hair_color: 'none',
    skin_color: 'blue',
    eye_color: 'red',
    birth_year: '62BBY',
    gender: 'male',
    homeworld: 'https://swapi.dev/api/planets/40/',
    films: [],
    species: ['https://swapi.dev/api/species/25/'],
    vehicles: [],
    starships: [],
    created: '2014-12-20T21:17:50.422000Z',
    edited: '2014-12-20T21:17:50.422000Z',
    url: 'https://swapi.dev/api/people/102/',
  },
  {
    name: 'Asajj Ventress',
    height: '179',
    mass: '50',
    hair_color: 'none',
    skin_color: 'pale',
    eye_color: 'blue',
    birth_year: '50BBY',
    gender: 'female',
    homeworld: 'https://swapi.dev/api/planets/43/',
    films: [],
    species: ['https://swapi.dev/api/species/30/'],
    vehicles: [],
    starships: [],
    created: '2014-12-20T21:17:50.423000Z',
    edited: '2014-12-20T21:17:50.423000Z',
    url: 'https://swapi.dev/api/people/103/',
  },
  {
    name: 'Savage Opress',
    height: '218',
    mass: '88',
    hair_color: 'none',
    skin_color: 'yellow',
    eye_color: 'yellow',
    birth_year: '54BBY',
    gender: 'male',
    homeworld: 'https://swapi.dev/api/planets/43/',
    films: [],
    species: ['https://swapi.dev/api/species/22/'],
    vehicles: [],
    starships: [],
    created: '2014-12-20T21:17:50.424000Z',
    edited: '2014-12-20T21:17:50.424000Z',
    url: 'https://swapi.dev/api/people/104/',
  },
  {
    name: 'Darth Maul',
    height: '175',
    mass: '80',
    hair_color: 'none',
    skin_color: 'red',
    eye_color: 'yellow',
    birth_year: '54BBY',
    gender: 'male',
    homeworld: 'https://swapi.dev/api/planets/43/',
    films: ['https://swapi.dev/api/films/4/'],
    species: ['https://swapi.dev/api/species/22/'],
    vehicles: ['https://swapi.dev/api/vehicles/42/'],
    starships: ['https://swapi.dev/api/starships/41/'],
    created: '2014-12-19T16:57:31.319000Z',
    edited: '2014-12-20T21:17:50.375000Z',
    url: 'https://swapi.dev/api/people/44/',
  },
  // Additional Bounty Hunters
  {
    name: 'IG-88',
    height: '200',
    mass: '140',
    hair_color: 'none',
    skin_color: 'metal',
    eye_color: 'red',
    birth_year: 'unknown',
    gender: 'none',
    homeworld: 'https://swapi.dev/api/planets/28/',
    films: ['https://swapi.dev/api/films/2/'],
    species: ['https://swapi.dev/api/species/2/'],
    vehicles: [],
    starships: [],
    created: '2014-12-15T12:51:10.076000Z',
    edited: '2014-12-20T21:17:50.351000Z',
    url: 'https://swapi.dev/api/people/23/',
  },
  {
    name: 'Bossk',
    height: '190',
    mass: '113',
    hair_color: 'none',
    skin_color: 'green',
    eye_color: 'red',
    birth_year: '53BBY',
    gender: 'male',
    homeworld: 'https://swapi.dev/api/planets/29/',
    films: ['https://swapi.dev/api/films/2/'],
    species: ['https://swapi.dev/api/species/7/'],
    vehicles: [],
    starships: [],
    created: '2014-12-15T12:53:49.297000Z',
    edited: '2014-12-20T21:17:50.355000Z',
    url: 'https://swapi.dev/api/people/24/',
  },
  {
    name: 'Dengar',
    height: '183',
    mass: '78',
    hair_color: 'brown',
    skin_color: 'light',
    eye_color: 'brown',
    birth_year: 'unknown',
    gender: 'male',
    homeworld: 'https://swapi.dev/api/planets/28/',
    films: ['https://swapi.dev/api/films/2/'],
    species: [],
    vehicles: [],
    starships: [],
    created: '2014-12-15T12:56:32.683000Z',
    edited: '2014-12-20T21:17:50.357000Z',
    url: 'https://swapi.dev/api/people/69/',
  },
  // Imperial Officers
  {
    name: 'Grand Moff Tarkin',
    height: '180',
    mass: 'unknown',
    hair_color: 'auburn, grey',
    skin_color: 'fair',
    eye_color: 'blue',
    birth_year: '64BBY',
    gender: 'male',
    homeworld: 'https://swapi.dev/api/planets/21/',
    films: ['https://swapi.dev/api/films/1/'],
    species: [],
    vehicles: [],
    starships: [],
    created: '2014-12-10T16:26:56.138000Z',
    edited: '2014-12-20T21:17:50.330000Z',
    url: 'https://swapi.dev/api/people/12/',
  },
  {
    name: 'Admiral Ozzel',
    height: '180',
    mass: '85',
    hair_color: 'brown',
    skin_color: 'light',
    eye_color: 'brown',
    birth_year: 'unknown',
    gender: 'male',
    homeworld: 'https://swapi.dev/api/planets/28/',
    films: ['https://swapi.dev/api/films/2/'],
    species: [],
    vehicles: [],
    starships: [],
    created: '2014-12-15T12:49:32.457000Z',
    edited: '2014-12-20T21:17:50.349000Z',
    url: 'https://swapi.dev/api/people/105/',
  },
  {
    name: 'Admiral Piett',
    height: '175',
    mass: '80',
    hair_color: 'brown',
    skin_color: 'light',
    eye_color: 'brown',
    birth_year: 'unknown',
    gender: 'male',
    homeworld: 'https://swapi.dev/api/planets/28/',
    films: ['https://swapi.dev/api/films/2/'],
    species: [],
    vehicles: [],
    starships: [],
    created: '2014-12-15T12:49:32.457000Z',
    edited: '2014-12-20T21:17:50.349000Z',
    url: 'https://swapi.dev/api/people/106/',
  },
  // Ewoks
  {
    name: 'Wicket W. Warrick',
    height: '88',
    mass: '20',
    hair_color: 'brown',
    skin_color: 'brown',
    eye_color: 'brown',
    birth_year: '8BBY',
    gender: 'male',
    homeworld: 'https://swapi.dev/api/planets/7/',
    films: ['https://swapi.dev/api/films/3/'],
    species: ['https://swapi.dev/api/species/9/'],
    vehicles: [],
    starships: [],
    created: '2014-12-18T11:21:58.954000Z',
    edited: '2014-12-20T21:17:50.332000Z',
    url: 'https://swapi.dev/api/people/30/',
  },
  {
    name: 'Logray',
    height: '88',
    mass: '20',
    hair_color: 'grey',
    skin_color: 'brown',
    eye_color: 'brown',
    birth_year: 'unknown',
    gender: 'male',
    homeworld: 'https://swapi.dev/api/planets/7/',
    films: ['https://swapi.dev/api/films/3/'],
    species: ['https://swapi.dev/api/species/9/'],
    vehicles: [],
    starships: [],
    created: '2014-12-18T11:26:29.426000Z',
    edited: '2014-12-20T21:17:50.334000Z',
    url: 'https://swapi.dev/api/people/31/',
  },
  // Jawas and Tusken Raiders
  {
    name: 'Jawa',
    height: '165',
    mass: 'unknown',
    hair_color: 'n/a',
    skin_color: 'brown',
    eye_color: 'orange',
    birth_year: 'unknown',
    gender: 'n/a',
    homeworld: 'https://swapi.dev/api/planets/1/',
    films: ['https://swapi.dev/api/films/1/'],
    species: ['https://swapi.dev/api/species/5/'],
    vehicles: ['https://swapi.dev/api/vehicles/36/'],
    starships: [],
    created: '2014-12-10T15:52:14.024000Z',
    edited: '2014-12-20T21:17:50.317000Z',
    url: 'https://swapi.dev/api/people/8/',
  },
  {
    name: 'Tusken Raider',
    height: '180',
    mass: '30',
    hair_color: 'n/a',
    skin_color: 'grey',
    eye_color: 'unknown',
    birth_year: 'unknown',
    gender: 'n/a',
    homeworld: 'https://swapi.dev/api/planets/1/',
    films: ['https://swapi.dev/api/films/1/'],
    species: ['https://swapi.dev/api/species/4/'],
    vehicles: ['https://swapi.dev/api/vehicles/20/'],
    starships: [],
    created: '2014-12-10T15:53:32.628000Z',
    edited: '2014-12-20T21:17:50.323000Z',
    url: 'https://swapi.dev/api/people/19/',
  },
  // Additional Aliens
  {
    name: 'Watto',
    height: '137',
    mass: 'unknown',
    hair_color: 'black',
    skin_color: 'blue, grey',
    eye_color: 'yellow',
    birth_year: 'unknown',
    gender: 'male',
    homeworld: 'https://swapi.dev/api/planets/34/',
    films: ['https://swapi.dev/api/films/4/'],
    species: ['https://swapi.dev/api/species/20/'],
    vehicles: [],
    starships: [],
    created: '2014-12-19T17:48:54.647000Z',
    edited: '2014-12-20T21:17:50.395000Z',
    url: 'https://swapi.dev/api/people/40/',
  },
  {
    name: 'Sebulba',
    height: '112',
    mass: '40',
    hair_color: 'none',
    skin_color: 'grey, red',
    eye_color: 'orange',
    birth_year: 'unknown',
    gender: 'male',
    homeworld: 'https://swapi.dev/api/planets/33/',
    films: ['https://swapi.dev/api/films/4/'],
    species: ['https://swapi.dev/api/species/12/'],
    vehicles: ['https://swapi.dev/api/vehicles/46/'],
    starships: [],
    created: '2014-12-19T17:43:53.348000Z',
    edited: '2014-12-20T21:17:50.393000Z',
    url: 'https://swapi.dev/api/people/41/',
  },
  {
    name: 'Nute Gunray',
    height: '191',
    mass: '90',
    hair_color: 'none',
    skin_color: 'mottled green',
    eye_color: 'red',
    birth_year: 'unknown',
    gender: 'male',
    homeworld: 'https://swapi.dev/api/planets/18/',
    films: ['https://swapi.dev/api/films/4/'],
    species: ['https://swapi.dev/api/species/18/'],
    vehicles: [],
    starships: [],
    created: '2014-12-19T17:05:57.357000Z',
    edited: '2014-12-20T21:17:50.377000Z',
    url: 'https://swapi.dev/api/people/33/',
  },
  {
    name: 'Rune Haako',
    height: '196',
    mass: '85',
    hair_color: 'none',
    skin_color: 'grey',
    eye_color: 'orange',
    birth_year: 'unknown',
    gender: 'male',
    homeworld: 'https://swapi.dev/api/planets/18/',
    films: ['https://swapi.dev/api/films/4/'],
    species: ['https://swapi.dev/api/species/18/'],
    vehicles: [],
    starships: [],
    created: '2014-12-19T17:07:35.696000Z',
    edited: '2014-12-20T21:17:50.379000Z',
    url: 'https://swapi.dev/api/people/34/',
  },
];

const BASE_URL = 'https://swapi.py4e.com/api/'; //fucking finally
const MAX_RETRIES = 2;
const RETRY_DELAY = 1000;
const ITEMS_PER_PAGE = 10;

const createMockResponse = (
  searchTerm: string = '',
  page: number = 1
): APIResponse => {
  const filteredCharacters = searchTerm
    ? MOCK_CHARACTERS.filter((char) =>
        char.name.toLowerCase().includes(searchTerm.toLowerCase())
      )
    : MOCK_CHARACTERS;

  // Simulate pagination for mock data
  const startIndex = (page - 1) * ITEMS_PER_PAGE;
  const endIndex = startIndex + ITEMS_PER_PAGE;
  const paginatedResults = filteredCharacters.slice(startIndex, endIndex);

  const totalPages = Math.ceil(filteredCharacters.length / ITEMS_PER_PAGE);

  return {
    count: filteredCharacters.length,
    next: page < totalPages ? `${BASE_URL}/people/?page=${page + 1}` : null,
    previous: page > 1 ? `${BASE_URL}/people/?page=${page - 1}` : null,
    results: paginatedResults,
  };
};

const delay = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms));

export const createPaginationInfo = (
  response: APIResponse,
  currentPage: number
): PaginationInfo => {
  const totalPages = Math.ceil(response.count / ITEMS_PER_PAGE);

  return {
    currentPage,
    totalPages,
    totalCount: response.count,
    hasNext: response.next !== null,
    hasPrevious: response.previous !== null,
  };
};

export class APIService {
  static async searchCharacters(
    searchTerm: string = '',
    page: number = 1,
    retryCount = 0
  ): Promise<APIResponse> {
    try {
      let url = `${BASE_URL}/people/`;
      const params = new URLSearchParams();

      if (searchTerm) {
        params.append('search', searchTerm);
      }

      params.append('page', page.toString());

      if (params.toString()) {
        const decodedURL = url + `?${params.toString()}`;
        url = encodeURI(decodedURL);
      }

      const controller = new AbortController();
      const timeoutId = setTimeout(() => controller.abort(), 10000);

      const response = await fetch(url, {
        method: 'GET',
        headers: {
          Accept: 'application/json',
          'Content-Type': 'application/json',
        },
        signal: controller.signal,
      });

      clearTimeout(timeoutId);

      if (!response.ok) {
        if (response.status >= 400 && response.status < 500) {
          throw new Error(
            `Client error (${response.status}): ${response.statusText}. Please check your request and try again.`
          );
        }

        if (response.status >= 500) {
          throw new Error(
            `Server error (${response.status}): ${response.statusText}. The service is temporarily unavailable.`
          );
        }

        throw new Error(
          `Request failed with status ${response.status}: ${response.statusText}`
        );
      }

      const data = await response.json();
      return data;
    } catch (error) {
      if (error instanceof Error) {
        if (error.name === 'AbortError') {
          if (retryCount < MAX_RETRIES) {
            console.log(
              `Request timed out, retrying... (${retryCount + 1}/${MAX_RETRIES})`
            );
            await delay(RETRY_DELAY * (retryCount + 1));
            return this.searchCharacters(searchTerm, page, retryCount + 1);
          }
          console.warn(
            'Request timed out after multiple attempts. Using enhanced mock data as fallback.'
          );
          return createMockResponse(searchTerm, page);
        }

        if (
          error.message.includes('Failed to fetch') ||
          error.message.includes('NetworkError')
        ) {
          if (retryCount < MAX_RETRIES) {
            console.log(
              `Network error, retrying... (${retryCount + 1}/${MAX_RETRIES})`
            );
            await delay(RETRY_DELAY * (retryCount + 1));
            return this.searchCharacters(searchTerm, page, retryCount + 1);
          }
          console.warn(
            'Network error: Unable to connect to the Star Wars API. Using enhanced mock data as fallback.'
          );
          return createMockResponse(searchTerm, page);
        }

        if (error.message.includes('CORS')) {
          console.warn(
            'CORS error: Unable to access the Star Wars API. Using enhanced mock data as fallback.'
          );
          return createMockResponse(searchTerm, page);
        }

        throw error;
      }

      throw new Error('An unexpected error occurred while fetching data.');
    }
  }
}
